### ISSUE TITLE
Project Reviews

### ISSUE THREAD

**Issue by syahrulhamdani** [d-wdj/H8_PTP_Final_Image#1]
First impression: very thorough notebook!

Some reviews you may want to consider:
* Great introduction in each section!
* I see you've trained multiple models. You may want to add some descriptions for each model architecture in the `README.md`, how each model yields different metrics ([see this](https://github.com/qubvel/efficientnet#models)). Also, by convention, we don't need to specify the stride of max-pooling layers if they're all the same. Just give a remark above or below it informing you used max-pooling right after convolutional layer with stride 2, for example.

Overall, you're doing great!

**Comment by d-wdj** [comment]
Thanks!

I've edited and the ```README.md``` as per your review. Instructions on how to use the model and do DIY prediction has also been added.
